添加 gbi 功能和代码
baidubce/app-builder pull request #21
Opened 2023-12-26 02:28 UTC by cjopengler

1. gbi 问表
    1.1 问表代码
    1.2 问表 readme
2. gbi 选表
    2.1 选表代码
    2.2 问表 readme
3. cookbook - gbi 选表&问表的 总体调用流程

2023-12-26 02:43 UTC, guru4elephant requested changes
please follow the comments

2023-12-26 02:43 UTC, guru4elephant commented on appbuilder/__init__.py
> +from .core.components.gbi.nl2sql.component import GBINL2Sql
有包名的情况下，不需要加GBI前缀

2023-12-26 02:43 UTC, guru4elephant commented on appbuilder/__init__.py
> +from .core.components.gbi.select_table.component import GBISelectTable
有包名的情况下，不需要加GBI前缀

2023-12-26 02:43 UTC, guru4elephant commented on appbuilder/core/components/gbi/basic.py
> +class NL2SqlResult(object):
用Pydantic的BaseModel就可以，不用写这么多

2023-12-26 02:43 UTC, guru4elephant commented on appbuilder/core/components/gbi/basic.py
> +    """
用Pydantic的BaseModel就可以，不用写这么多

2023-12-26 02:43 UTC, guru4elephant commented on appbuilder/core/components/gbi/basic.py
> +    """
用Pydantic的BaseModel就可以，不用写这么多

2023-12-26 02:43 UTC, guru4elephant commented on appbuilder/core/components/gbi/basic.py
> +    "ERNIE-Bot 4.0", "ERNIE-Bot-8K", "ERNIE-Bot", "ERNIE-Bot-turbo", "EB-turbo-AppBuilder"
不要在这里指定名字，名字获取有统一的参数，对应的名字也是从千帆动态获取。

2023-12-26 02:43 UTC, guru4elephant commented on appbuilder/core/components/gbi/nl2sql/README.md
> +nl2sql_result_message = gbi_nl2sql(message=msg, session=session)
第一个字段不用写message，输入的Message直接带入即可。session如果是动态数据，也用Message来表示。

2023-12-26 02:43 UTC, guru4elephant commented on appbuilder/core/components/gbi/nl2sql/README.md
> +#### GBISessionRecord 初始化参数
如果没有特殊要求，直接用Message封装即可。额外定义数据结构使用成本较高。

2023-12-26 02:43 UTC, guru4elephant commented on appbuilder/core/components/gbi/nl2sql/component.py
> +        """
按照MetaComponent来写比较好，这样会有很多自动化的参数校验，请参考其他Component的实现。

2023-12-26 02:43 UTC, guru4elephant commented on appbuilder/core/components/gbi/select_table/README.md
> +GBI 选表，根据提供的表的描述信息以及 query 选择对应的表.
这个介绍，用户不太容易理解。

2023-12-26 02:43 UTC, guru4elephant commented on appbuilder/core/components/gbi/select_table/component.py
> +    def __init__(self, model_name: str, table_descriptions: Dict[str, str],
参考MetaComponent写法来定义参数。

2023-12-26 11:46 UTC, cjopengler commented on appbuilder/core/components/gbi/nl2sql/README.md
> +#### GBISessionRecord 初始化参数
ColumInfo 和 SessionRecord 要定义下，结构有点复杂，很容易写错。所以保留这两个结构

2023-12-27 02:42 UTC, guru4elephant approved these changes
LGTM

2023-12-27 02:42 UTC, guru4elephant commented on appbuilder/core/components/gbi/select_table/README.md
> +select_table_result_message = select_table(Message({"query": "列出超市中的所有数据"}))
选表是否需要调用大模型

2023-12-27 03:02 UTC, cjopengler commented on appbuilder/core/components/gbi/select_table/README.md
> +select_table_result_message = select_table(Message({"query": "列出超市中的所有数据"}))
需要

2023-12-27 04:34 UTC, merged