增加模型列表获取的SDK
baidubce/app-builder pull request #29
Opened 2023-12-29 03:16 UTC by HorseDream

1、utils目录下新建model_util.py文件，包含Models工具类，提供list()方法
2、utils.py里面新建get_model_list()工具方法，供用户调用

2024-01-03 03:47 UTC, seiriosPlus commented on appbuilder/tests/test_get_model_list.py
> +        self.assertIsNotNone(response)
只验证 返回是否为空， 需要进一步校验返回值的正确性

2024-01-03 03:47 UTC, seiriosPlus commented on appbuilder/tests/test_get_model_list.py
> +        self.assertIsNotNone(response)
apiTypefilter=["chat"]， filter的chat是什么含义

2024-01-03 07:38 UTC, ide-rea requested changes

2024-01-03 07:38 UTC, ide-rea commented on appbuilder/core/utils.py
> +def get_model_list(secret_key: str = "", apiTypefilter: List[str] = [], is_available: bool = False):
get_model_list函数的返回类型是不是也可以说明下

2024-01-03 07:38 UTC, ide-rea commented on appbuilder/core/utils.py
> +            models.append(mapped_name)
是不是一次遍历就拿到模型列表，类似这样
```python
models = []
for common_model in response.result.common:
    if is_available and common_model.chargeStatus not in ["OPENED", "FREE"]:
        continue
    mapped_name = map_model_name(common_model.name)
    models.append(mapped_name)
      
      
for custom_model in response.result.custom:
    if is_available and custom_model.chargeStatus not in ["OPENED", "FREE"]:
        continue
    mapped_name = map_model_name(custom_model.name)
    models.append(mapped_name)
```

2024-01-03 07:38 UTC, ide-rea commented on appbuilder/core/utils.py
> +def get_model_list(secret_key: str = "", apiTypefilter: List[str] = [], is_available: bool = False):
确实需要apiTypefilter吗，如果需要的可以统一写成下划线

2024-01-03 07:57 UTC, ide-rea commented on appbuilder/core/utils.py
> +            models.append(mapped_name)
还有一种可能的方式，使用一个迭代器，将通用模型与定制化模型连接起来，再进行遍历
`
import itertools
for  model in itertools.chain(response.result.common, response.result.custom):
   # 依次对模型进行处理
`

2024-01-03 08:18 UTC, HorseDream commented on appbuilder/tests/test_get_model_list.py
> +        self.assertIsNotNone(response)
就是只返回千帆的对话Chat模型

2024-01-03 08:37 UTC, ide-rea requested changes

2024-01-03 08:37 UTC, ide-rea commented on appbuilder/core/utils.py
> +    return models
可以使用一个迭代器，将通用模型与定制化模型连接起来，再进行遍历
```python
import itertools
for  model in itertools.chain(response.result.common, response.result.custom):
    if is_available and common_model.chargeStatus not in ["OPENED", "FREE"]:
        continue
    mapped_name = map_model_name(common_model.name)
    models.append(mapped_name)
```

2024-01-04 08:16 UTC, seiriosPlus approved these changes
LGTM

2024-01-04 08:16 UTC, merged