新增rag_with_baidusearch_pro组件
baidubce/app-builder pull request #329
Opened 2024-05-27 09:10 UTC by Xenon0220

2024-05-27 11:24 UTC, barrierye commented on appbuilder/tests/test_rag_baidu_search_pro.py
> +        self.assertIsNotNone(answer.content)
判断字符串非空

2024-05-27 11:24 UTC, barrierye commented on appbuilder/tests/test_rag_baidu_search_pro.py
> +        self.assertIsNotNone(answer.extra)
判断references非空

2024-05-27 11:24 UTC, barrierye commented on appbuilder/tests/test_rag_baidu_search_pro.py
> +            self.assertIsNotNone(content)
判断字符串非空

2024-05-27 11:24 UTC, barrierye commented on appbuilder/tests/test_rag_baidu_search_pro.py
> +            self.assertIsNotNone(extra)
判断references非空

2024-05-27 11:25 UTC, barrierye requested changes
需要README

2024-05-28 10:29 UTC, MrChengmo commented on appbuilder/core/components/rag_with_baidu_search_pro/README.md
> +references = result.extra
返回参数说明中没有`extra`的部分

2024-05-28 10:29 UTC, MrChengmo commented on appbuilder/core/components/rag_with_baidu_search_pro/__init__.py
> +"""
换成开源代码库的开源license头，参考其他代码文件

2024-05-28 10:29 UTC, MrChengmo commented on appbuilder/core/components/rag_with_baidu_search_pro/component.py
> +"""
更换license

2024-05-28 10:29 UTC, MrChengmo commented on appbuilder/core/components/rag_with_baidu_search_pro/parse_rag_pro_response.py
> +"""
更换license

2024-05-28 10:29 UTC, MrChengmo commented on appbuilder/core/components/rag_with_baidu_search/README.md
>  百度搜索（BaiduSearch），通过百度搜索引擎搜索相关内容。
添加推荐用户使用pro版的说明，在此处加上普通和pro版的对比（表格）

2024-05-28 10:29 UTC, MrChengmo commented on appbuilder/core/components/rag_with_baidu_search_pro/component.py
> +            hide_corner_markers=True
此处缺少参数的校验，建议通过pydantic进行类型和数值范围校验

2024-05-29 04:22 UTC, MrChengmo approved these changes
LGTM

2024-05-29 04:22 UTC, merged