升级AgentBase，数据管理能力更加易用
baidubce/app-builder pull request #36
Opened 2024-01-05 10:33 UTC by barrierye

2024-01-06 03:56 UTC, guru4elephant requested changes
user_session的用法表意需要更明确，更易用一些。关键数据结构的字段说明详细补充下。

2024-01-06 03:56 UTC, guru4elephant commented on appbuilder/core/user_session.py
> +    会话数据模型
增加详细的文档，尤其是对每个字段的文字说明

2024-01-06 03:56 UTC, guru4elephant commented on appbuilder/core/user_session.py
> +            limit (int): 获取最近的几条 session 数据
最近limit条Message数据

2024-01-08 03:06 UTC, guru4elephant requested changes

2024-01-08 03:06 UTC, guru4elephant commented on appbuilder/core/agent.py
> +                    user_session = UserSession()
这个地方，如果只是想运行PlaygroundWithHistory，例如 playground = PlaygroundWithHistory(), playground.run(xxx)，这样

2024-01-08 03:06 UTC, guru4elephant commented on appbuilder/core/agent.py
> +            agent = AgentBase(component=PlaygroundWithHistory())
AgentBase这个名字不太合适，是不是可以叫AgentRuntime

2024-01-08 07:30 UTC, barrierye commented on appbuilder/core/agent.py
> +                    user_session = UserSession()
当前是会直接报错（没有初始化session上下文，You need to use UserSession in AgentRuntime.serve or AgentRuntime.chainlit_demo），这个可以给一个默认的上下文跑起来

2024-01-08 11:56 UTC, barrierye commented on appbuilder/core/agent.py
> +                    user_session = UserSession()
当直接用Component.run时，使用内存管理session数据

2024-01-08 11:57 UTC, barrierye commented on appbuilder/core/agent.py
> +            agent = AgentBase(component=PlaygroundWithHistory())
更名成AgentRuntime了

2024-01-08 11:57 UTC, barrierye commented on appbuilder/core/user_session.py
> +            limit (int): 获取最近的几条 session 数据
已更新

2024-01-08 11:57 UTC, barrierye commented on appbuilder/core/user_session.py
> +    会话数据模型
已更新

2024-01-09 16:01 UTC, guru4elephant approved these changes
LGTM

2024-01-10 05:35 UTC, seiriosPlus approved these changes
LGTM

2024-01-10 05:35 UTC, merged