新增百度搜索rag组件（RAGwithBaiduSearch）
baidubce/app-builder pull request #41
Opened 2024-01-11 06:58 UTC by Xenon0220

2024-01-11 07:01 UTC, barrierye commented on appbuilder/core/components/llms/base.py
> +from itertools import tee
不需要tee

2024-01-11 07:05 UTC, barrierye requested changes

2024-01-11 07:05 UTC, barrierye commented on appbuilder/core/components/llms/base.py
> +    def __init__(self, response, stream: bool = False, rag_baidu_search: bool = False):
base基类不能有rag_baidu_search参数

2024-01-11 07:05 UTC, barrierye commented on appbuilder/core/components/llms/base.py
> +    def gene_response(self, response, stream: bool = False, rag_baidu_search: bool = False):
base基类不能有rag_baidu_search参数

2024-01-11 07:05 UTC, barrierye commented on appbuilder/core/components/llms/base.py
> +        response = CompletionResponse(response, stream, rag_baidu_search)
base基类不能有rag_baidu_search参数

2024-01-11 07:05 UTC, barrierye commented on appbuilder/core/components/llms/base.py
> +                   retry: int = 0, rag_baidu_search: bool = False) -> CompletionResponse:
base基类不能有rag_baidu_search参数

2024-01-11 07:05 UTC, barrierye commented on appbuilder/core/components/llms/base.py
> +               "/rag_with_baidu_search")
需要删除

2024-01-11 07:05 UTC, barrierye commented on appbuilder/core/components/llms/base.py
> +        return self.gene_response(response, stream, rag_baidu_search)
base基类不能有rag_baidu_search参数

2024-01-11 08:58 UTC, barrierye requested changes

2024-01-11 08:58 UTC, barrierye commented on appbuilder/core/components/rag_with_baidu_search/README.md
> +它利用百度搜索引擎来实现对候选文本的检索。它可以接受一个问题作为输入，并返回一些与问题相关的网页作为候选文本。
RAG with BaiduSearch是基于生成式大模型的问答组件，使用百度搜索引擎检索候选文本进行检索增强。

2024-01-11 08:58 UTC, barrierye commented on appbuilder/core/components/rag_with_baidu_search/README.md
> +print(result)
加一下如何获取references

2024-01-11 08:58 UTC, barrierye commented on appbuilder/core/components/rag_with_baidu_search/README.md
> +- `temperature (float, 可选)`: 模型配置的温度参数，用于调整模型的生成概率。取值范围为 0.0 到 1.0，其中较低的值使生成更确定性，较高的值使生成更多样性。默认值为 1e-10。
缺少 top_p

2024-01-11 08:58 UTC, barrierye commented on appbuilder/core/components/rag_with_baidu_search/README.md
> +- `emphasis (bool, 可选)`: 重点强调开关，如果为 True，则启用该能力。默认为 False。开启该功能时，回复结果中会高亮显示关键部分的内容。
这里字段需要和mrc的对齐

2024-01-11 08:58 UTC, barrierye commented on appbuilder/core/components/rag_with_baidu_search/README.md
> +                                            instruction=instruction)
instruction应该是message类型

2024-01-11 08:58 UTC, barrierye commented on appbuilder/core/components/rag_with_baidu_search/component.py
> +    context_out: str = Field(...,
需要删除

2024-01-11 08:58 UTC, barrierye commented on appbuilder/core/components/rag_with_baidu_search/component.py
> +    emphasis: bool = Field(...,
字段名需要和mrc对齐

2024-01-11 08:58 UTC, barrierye commented on appbuilder/core/components/rag_with_baidu_search/component.py
> +                "__system__": "你是问答助手，在回答问题前需要加上“很高兴为您解答：”"
需要去除

2024-01-11 08:58 UTC, barrierye commented on appbuilder/core/components/rag_with_baidu_search/component.py
> +            emphasis=False, friendliness=False, reference=False, stream=False, temperature=1e-10, instruction=None):
instruction需要为message类型

2024-01-11 08:58 UTC, barrierye commented on appbuilder/tests/test_rag_baidu_search.py
> +        os.environ["APPBUILDER_TOKEN"] = ("Bearer bce-v3/ALTAK-tpJqnbAvTivWEAclPibrT"
删除

2024-01-11 08:58 UTC, barrierye commented on appbuilder/tests/test_rag_baidu_search.py
> +            print(answer.extra)
assert检查

2024-01-11 11:32 UTC, barrierye requested changes

2024-01-11 11:32 UTC, barrierye commented on appbuilder/core/components/llms/base.py
> +    top_p: confloat(gt=0.0, le=1.0) = Field(default=1e-10, description="模型的采样范围，范围从 0.0 到 1.0。")
模型的top_p参数，default=0 和现有的对齐

2024-01-11 11:32 UTC, barrierye commented on appbuilder/core/components/rag_with_baidu_search/README.md
> +- `top_p (float, 可选)`: 模型配置的采样范围，top_p值越高，输出与训练文本越相似，top_p值越低，输出越有创意和变化。它可用于使输出更适合特定用例。取值范围为 0.0 到 1.0，默认值为 1e-10。
模型配置的top_p参数，top_p值越高输出文本越多样，top_p值越低输出文本越稳定。取值范围为 0.0 到 1.0，默认值为 0。

2024-01-11 11:32 UTC, barrierye commented on appbuilder/core/components/rag_with_baidu_search/component.py
> +class BaiduSearchArgs(ComponentArguments):
RAGWithBaiduSearhArgs

2024-01-11 11:32 UTC, barrierye commented on appbuilder/core/components/rag_with_baidu_search/component.py
> +    百度search提示词配置
RAG with BaiduSearh 配置

2024-01-11 11:32 UTC, barrierye commented on appbuilder/core/components/rag_with_baidu_search/component.py
> +        super().__init__(BaiduSearchArgs, model=model)
super().__init__(RAGWithBaiduSearch, model=model)

2024-01-11 11:32 UTC, barrierye commented on appbuilder/tests/test_rag_baidu_search.py
> +            self.assertIsNotNone(answer)
加一个answer.content和answer.extra判断

2024-01-11 11:32 UTC, barrierye commented on appbuilder/tests/test_rag_baidu_search.py
> +            self.assertIsNotNone(answer)
answer.extra

2024-01-11 12:46 UTC, barrierye approved these changes

2024-01-11 14:12 UTC, seiriosPlus requested changes

2024-01-11 14:12 UTC, seiriosPlus commented on appbuilder/tests/test_rag_baidu_search.py
> +        os.environ["APPBUILDER_TOKEN"] = ("Bearer bce-v3/ALTAK-tpJqnbAvTivWEAclPibrT"
密钥不要写环境变量，删除！

2024-01-11 14:12 UTC, seiriosPlus commented on appbuilder/core/components/rag_with_baidu_search/component.py
> +            highlight=False, friendly=False, cite=False, stream=False, temperature=1e-10, top_p=1e-10, instruction=None):
instruction 变量写在 stream前面.

2024-01-11 14:14 UTC, seiriosPlus requested changes

2024-01-11 14:14 UTC, seiriosPlus commented on appbuilder/core/components/rag_with_baidu_search/README.md
> +- `instruction (obj:Message, 可选)`: 可设定人设，如：你是问答助手，在回答问题前需要加上“很高兴为您解答：”
readme里面补充一下返回的典型样例.

2024-01-12 05:44 UTC, seiriosPlus approved these changes
LGTM

2024-01-12 05:45 UTC, merged