增加RagWithBaidusearch的readme返回参数说明
baidubce/app-builder pull request #73
Opened 2024-01-18 03:47 UTC by Xenon0220

2024-01-18 03:51 UTC, barrierye requested changes

2024-01-18 03:51 UTC, barrierye commented on appbuilder/core/components/rag_with_baidu_search/README.md
> +### 返回参数说明
放在返回样例上面，并且说明是extra字段；
竖着写，两列：字段、字段说明

2024-01-18 04:08 UTC, barrierye requested changes

2024-01-18 04:08 UTC, barrierye commented on appbuilder/core/components/rag_with_baidu_search/README.md
> +extra字段：
返回的message中extra字段包含了BaiduSearch结果，具体字段说明如下

2024-01-18 04:13 UTC, barrierye approved these changes

2024-01-20 16:25 UTC, guru4elephant commented on appbuilder/core/components/rag_with_baidu_search/README.md
> +| id      | 网页链接   |
网页链接为什么不是url，而是id

2024-01-20 16:28 UTC, barrierye commented on appbuilder/core/components/rag_with_baidu_search/README.md
> +| id      | 网页链接   |
这里是内部Engine的原始字段，没有做rename

2024-01-20 16:38 UTC, guru4elephant commented on appbuilder/core/components/rag_with_baidu_search/README.md
> +| id      | 网页链接   |
但这个不是会返回给用户的么

2024-01-20 16:40 UTC, barrierye commented on appbuilder/core/components/rag_with_baidu_search/README.md
> +| id      | 网页链接   |
那还是在SDK侧做下rename吧

2024-01-22 03:40 UTC, barrierye requested changes

2024-01-22 03:40 UTC, barrierye commented on appbuilder/core/components/llms/base.py
> +                        for item in result_list:
需要做一个判断，这里可能会有不同的tool，你这个rename只能针对该种tool

2024-01-22 03:40 UTC, barrierye commented on appbuilder/core/components/rag_with_baidu_search/component.py
> +        if stream is False:
应该在base修改

2024-01-22 07:05 UTC, barrierye requested changes

2024-01-22 07:05 UTC, barrierye commented on appbuilder/core/components/llms/base.py
> +    def process_result_list(result_list):
class ResultProcesser:

    def process(self, key, result_list):
        if key == 'search_baidu':
            rename_fields = {
                'id': 'url',
                'mock_id': 'ref_id',
                'content': 'content',
                'title': 'title',
            }
            renamed_list = []
            for result in result_list:
                renamed_list.append({rename_fields[k]: v for k, v in result.items()})
            return renamed_list
        else:
            raise TypeError(...)

2024-01-22 08:11 UTC, barrierye approved these changes

2024-01-22 08:15 UTC, seiriosPlus approved these changes

2024-01-22 08:15 UTC, merged